language: php

sudo: false

php:
    - 7.1

before_install:
    - pecl channel-update pecl.php.net
    - pecl config-set preferred_state beta; echo yes | pecl install apcu
    - phpenv config-add ./testing/travis.php.ini


install:
    - composer --no-interaction --no-progress install
    - composer show --installed

script: vendor/bin/phpunit
